- chai-immutable.js
- test/test.js
This is an updated version of #16. I dug into the problem a little deeper to get a better understanding and figured out the actual root cause (essentially, not calling the original `equal` function.
> Fix broken assert.equal assertion when not applied on a Collection

- README.md
- chai-immutable.js
- test/test.js
See #24 for more information.
@alexw668, could you give your opinion on the wording please?
> Precisions around deep equality

- test/test.js
This PR closes #20.
+45 tests, for a new total of 109 !
~~However... 3 tests are failing. I believe 2 of them are related to the same issue, but these new tests show at least 2 bugs.~~
Since this PR only add tests, it doesn't break the tests, it simply outputs a problem with the current library. For this reason, it can be merged and this will reflect that chai-immutable does not build properly via the Travis CI badge on the README.
But merging this also removes the possibility to automatically deploy on npm via Travis CI, which means both bugs need to be merged to be deployed, quite a pain.
> Reword, reorganize, and add tests

- chai-immutable.js
- test/test.js
Right now the check for whether an object is Immutable uses `instanceof Collection`, which returns false if different modules are using different copies of Immutable.
This PR replaces that with `Immutable.Iterable.isIterable` as advised here: http://stackoverflow.com/questions/31907470/how-to-check-if-object-is-immutable
> Use Iterable.isIterable for Immutable check

- CODE_OF_CONDUCT.md
Closes #40. Upstream Chai project has added a Code of Conduct so using it over here too.
Note that Chai is using v1.3.0 and I am adding v1.4.0 on purpose.
> Add Chai's Code of Conduct

- chai-immutable.js
- test/test.js
Property and deep property assertions, because I really like that syntax when I use `chai` with plain objects. :0)
```javascript
var obj = Immutable.fromJS({ x: 1 });
expect(obj).to.have.property('x', 1);
var obj = Immutable.fromJS({ x: 1, y: { x: 2, y: 3 } });
expect(obj).to.have.deep.property(['y', 'x'], 2);
```
Based on original `property()` here: https://github.com/chaijs/chai/blob/8e8a728921085351ecd050cd606b2ef6a1fb1338/lib/chai/core/assertions.js#L881
Like other methods in `chai-immutable`, falls back to original chai methods if the target object is not `isIterable()`.
100% code coverage for newly-added code. Also, I noticed that changing `chai.config.truncateThreshold` can make display of Immutable objects a lot nicer.
> Support Immutable with chai's property assertions

- chai-immutable.js
- test/test.js
It took me long enough, but this is the fix for the bug I was mentioning in https://github.com/astorije/chai-immutable/pull/53#issuecomment-213892782.
As opposed to the original `.split()`, re-using [Chai's original `parsePath` function](https://github.com/chaijs/chai/blob/d664ef4/lib/chai/utils/getPathInfo.js#L46-L74) lets us
- Have strings that start or end with indices
- Escape dots and brackets in string-based paths
@scottnonnenberg, once again, would you mind giving me your opinion and 👍 if you like it? :-)
Thanks!
> Fix parsing of string-based path for the property assertion

- chai-immutable.js
- test/test.js
Consider the following immutable object:
```js
var obj = new Map({
items: new List([
new Map({ name: 'Jane' }),
new Map({ name: 'John' }),
])
});
```
Without this change, the following passes:
```js
expect(obj).to.have.deep.property('items[0].name', 'Jane');
```
But the following fails:
```js
expect(obj).to.have.deep.property('items[1]', new Map({ name: 'Alice'}));
```
Which is a bit too bad for a library that offers assertions for immutable structures!
@scottnonnenberg, considering you contributed to this code, would you mind giving me your opinion and 👍 if you like it? :-)
Thanks!
> Allow passing immutable values in the property assertion

- .travis.yml
- README.md
- appveyor.yml
- package.json
Use https://www.npmjs.com/package/fulky that provides a compiler for Mocha, extracting JavaScript snippets from the README and running them as individual tests.
Fulky is ES6-only, so configurations for Travis CI and AppVeyor are not running it.
> Test JS examples in README

- README.md
- chai-immutable.js
- package.json
- test/test.js
DO NOT MERGE
Hi @astorije, I'm just going through some Chai plugins to see how much the upcoming Chai v4.0 breaks things (given that it has a number of breaking changes). I noticed one breaking change in this project regarding the `deep.property` assertion being renamed to `nested.property` in Chai v4.0. Also, there's a breaking change in Chai's `type-detect` library regarding capitalization which impacts this plugin.
This PR does the minimum required to get chai-immutable working in Chai v4.0, but doesn't actually update the chai dev dependency since v4.0 isn't officially released yet (thus the failed Travis build.)
BREAKING CHANGE: `deep.property` renamed to `nested.property`
> Update for Chai v4.0

- chai-immutable.js
- test/test.js
This shows a better diff of which keys are extra/missing rather than getting big strings dumped on the user
> Better diff output when comparing

- test/test.js
This follows up #67.
I did not investigate much, but I believe there was a change in `Chai`'s `AssertionError` or something in Chai v4 and while #67 passed the tests, I merged it after #69 triggering these failures.
> Fix tests around AssertionError messages

- .travis.yml
- appveyor.yml
- package.json
> Drop support for Node.js v0.10 and v0.12

- .travis.yml
- appveyor.yml
- package.json
- test/test.js
At the moment, PhantomJS is not ES6-compatible so a further commit that enables ES6 features is simply breaking it. Furthermore, this is not very useful at the moment, because it merely tests the loading of the plugin in a (headless) browser, nothing more.
I do plan to integrate better testing in browsers, and I do need to re-test the correct loading of these tests in a browser. In the meantime, loading `test/index.html` manually in a browser is a way to do that.
> Remove mocha-phantomjs test suite

- .eslintrc.yml
- chai-immutable.js
Closes #21.
Setting expectations for v2.0.0: `chai-immutable` is supported in Node and the browser. Anything else will need contributions :D
> Remove AMD check, as it was never supported anyway

- package.json
Specifically in version 3: this plugin would not work with < 3 anyway, and v4 has not been released yet.
> Mark Immutable.js as a `peerDependency`

- README.md
- chai-immutable.js
- test/test.js
Closes https://github.com/astorije/chai-immutable/issues/76.
BREAKING CHANGE: `.not.property` and `.not.nested.property` now pass when given both a key and value, and that key does not exist (it used to fail).
> Adapt `.property` (more specifically `.not.property`) to the Chai v4 changes

- README.md
- chai-immutable.js
- test/test.js
Resolves https://github.com/astorije/chai-immutable/issues/75: `.property` is the same as `.deep.property`, just like `.equal` is the same as ` .deep.equal`.
> Tests and clean ups around `.property`

- .eslintrc.yml
- README.md
- chai-immutable.js
- test/test.js
One addition of this change is that `.keys` is now compatible with `List`s and other iterable collections.
Resolves https://github.com/astorije/chai-immutable/issues/73.
> Re-sync `.keys` with Chai's native assertion, and add tests/support for `.deep.keys`

- README.md
- chai-immutable.js
By mirroring the Chai native one.
Follow-up of https://github.com/astorije/chai-immutable/pull/108.
> Improve documentation of `.property`

- README.md
See #52.
I also modified the snippet using the `eventually` method from `chai-as-promised`, because it expects a Promise to test against.
> Use ES6 syntax in README

- .eslintrc.yml
- test/test.js
One more step towards https://github.com/astorije/chai-immutable/issues/86.
Loosely inspired from https://github.com/chaijs/chai/pull/760.
> Add tests around `include` and deep equality

- README.md
- chai-immutable.js
- test/test.js
Include now allows immutable subsets as a valid input, making the behavior more like chai's behavior with objects.
References this issue: https://github.com/astorije/chai-immutable/issues/82
> include uses isSuperset

- .travis.yml
- chai-immutable.js
Copies isImmutable function from #83, but no conflicts and check for isImmutable only for .equal. Other places have valid checks for isIterable (.empty or .size is not available in Record)
> .equal now checks for isImmutable instead of isIterable

- README.md
- chai-immutable.js
- test/test.js
This MR adds `referenceEqual` BDD method and `referenceEqual` and `referenceNotEqual` TDD methods according to the discussion in #210.
Close #210.
> Implement reference comparison
